modLoader="javafml"
loaderVersion="[36.2.0,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Mnesikos/LilCritters/issues"

[[mods]]
    modId="lilcritters"
    version="${file.jarVersion}"
    displayName="Lil Critters Mod"
    #updateJSONURL=""
    displayURL="https://www.curseforge.com/minecraft/mc-mods/lil-critters"
    logoFile="logo.png"
    credits="Huge thank yous to everyone who helps pitch in on the details of Lil' Critters! Including Arty, Asheine, Fisk, Platinum, Shoresy, and SnazzyGator for art assets; Fisk, Lysaell, Redkoopa, and Shoresy for data book entries; and my lovely community for all of their input."
    authors="Mnesikos"
    description='''
A ZAWA mod addon, aiming to add some ambiance with little critters usually found in your very own backyards.
    '''

[[dependencies.lilcritters]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lilcritters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lilcritters]]
    modId="zawa"
    mandatory=true
    versionRange="[1.16.5-1.0.1-BeefBeta-Carnivora2,)"
    ordering="AFTER"
    side="BOTH"